export const CREATION_ACCURACY_RADIUS_IN_DEGREES =
  Number(process.env.CREATION_ACCURACY_RADIUS_IN_DEGREES) || 0.005;

export const LOCALIZATION_ACCURACY_RADIUS_IN_DEGREES =
  Number(process.env.LOCALIZATION_ACCURACY_RADIUS_IN_DEGREES) || 0.3;
